language: node_js
node_js: node
dist: xenial
notifications:
  email:
    recipients:
      - jwu1100@gmail.com
    on_success: always
    on_failure: always
services:
  - xvfb
before_script:
  - cd test
  - npm install
script:
  - node test
