version: 2

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/github-markdown-printer/test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: node test.js
      - store_artifacts:
          path: reference-screenshot.png
      - store_artifacts:
          path: test-screenshot.png
      - store_artifacts:
          path: screenshot-diff.png
