version: 2

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "test/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: cd test && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "test/package.json" }}
      - run: node test/test.js
      - store_artifacts:
          path: test/reference-screenshot.png
      - store_artifacts:
          path: test/test-screenshot.png
      - store_artifacts:
          path: test/screenshot-diff.png
