version: 2

workflows:
  version: 2
  test-commit:
    jobs:
      - test
  test-daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "test/package.json" }}
      - run: |
          cd test
          npm install
          node test
      - store_artifacts:
          path: test/reference-screenshot.png
      - store_artifacts:
          path: test/test-screenshot.png
      - store_artifacts:
          path: test/screenshot-diff.png
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "test/package.json" }}
