version: 2

workflows:
  version: 2
  test-commit:
    jobs:
      - test
  test-daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: cd test && npm install
      - run: node test/test.js
      - store_artifacts:
          path: test/screenshots
